# docker run --name daily-diet -e POSTGRESQL_USERNAME=docker -e POSTGRESQL_PASSWORD=docker -e 
# POSTGRESQL_DATABASE=apisolid -p 5432:5432 bitnami/postgresql

version: '3'

services:
  daily-diet:
    image: bitnami/postgresql
    ports: 
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=daily-diet